#!/usr/bin/env python3
from __future__ import annotations

import argparse
import ipaddress
import json
import re
import sys
from datetime import date, datetime
from pathlib import Path
from typing import Optional, Union
from urllib.request import Request, urlopen


SOURCE_URL = "https://openai.com/chatgpt-voice.json"
ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / "rules" / "production" / "ai" / "ChatGPTVoice.list"
Network = Union[ipaddress.IPv4Network, ipaddress.IPv6Network]


def load_source() -> object:
    request = Request(SOURCE_URL, headers={"User-Agent": "Tricooo-Rules-Voice-Sync/1.0"})
    with urlopen(request, timeout=20) as response:
        return json.load(response)


def extract_networks(payload: object) -> tuple[str, tuple[Network, ...]]:
    if not isinstance(payload, dict):
        raise ValueError("source must be a JSON object")
    creation_time = payload.get("creationTime")
    prefixes = payload.get("prefixes")
    if not isinstance(creation_time, str) or not creation_time:
        raise ValueError("source has no creationTime")
    if not isinstance(prefixes, list) or not prefixes:
        raise ValueError("source has no prefixes")

    networks: set[Network] = set()
    for item in prefixes:
        if not isinstance(item, dict):
            raise ValueError("prefix entry is not an object")
        values = [item[key] for key in ("ipv4Prefix", "ipv6Prefix") if key in item]
        if len(values) != 1 or not isinstance(values[0], str):
            raise ValueError("prefix entry must contain exactly one IP prefix")
        network = ipaddress.ip_network(values[0], strict=True)
        if network.prefixlen != network.max_prefixlen:
            raise ValueError(f"source prefix must be a host prefix: {network}")
        if not network.network_address.is_global:
            raise ValueError(f"source prefix is not globally routable: {network}")
        if network in networks:
            raise ValueError(f"source contains duplicate prefix: {network}")
        networks.add(network)

    ordered = tuple(
        sorted(
            networks,
            key=lambda network: (network.version, int(network.network_address), network.prefixlen),
        )
    )
    return creation_time, ordered


def current_review_date() -> str:
    if TARGET.exists():
        match = re.search(
            r"^# Last reviewed: (\d{4}-\d{2}-\d{2})$",
            TARGET.read_text(encoding="utf-8"),
            re.MULTILINE,
        )
        if match:
            return match.group(1)
    return date.today().isoformat()


def current_creation_time() -> Optional[str]:
    if not TARGET.exists():
        return None
    match = re.search(
        r"^# Source creation time: (.+)$",
        TARGET.read_text(encoding="utf-8"),
        re.MULTILINE,
    )
    return match.group(1).strip() if match else None


def parse_creation_time(value: str) -> datetime:
    parsed = datetime.fromisoformat(value.replace("Z", "+00:00"))
    if parsed.tzinfo is None:
        raise ValueError("creationTime must include a timezone")
    return parsed


def ensure_not_rollback(incoming: str, current: Optional[str]) -> None:
    incoming_time = parse_creation_time(incoming)
    if current is not None and incoming_time < parse_creation_time(current):
        raise ValueError("source creationTime is older than the checked-in snapshot")


def render(creation_time: str, networks: tuple[Network, ...], review_date: str) -> str:
    lines = [
        "# Purpose: Current OpenAI-published ChatGPT Voice media endpoints.",
        f"# Source: {SOURCE_URL}",
        f"# Source creation time: {creation_time}",
        "# Generated by: scripts/sync_chatgpt_voice.py",
        f"# Last reviewed: {review_date}",
    ]
    for network in networks:
        rule_type = "IP-CIDR" if network.version == 4 else "IP-CIDR6"
        lines.append(f"{rule_type},{network.with_prefixlen},no-resolve")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Synchronize OpenAI ChatGPT Voice IP prefixes")
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if the checked-in list differs from the current official JSON",
    )
    args = parser.parse_args()

    try:
        creation_time, networks = extract_networks(load_source())
        ensure_not_rollback(creation_time, current_creation_time())
        review_date = current_review_date() if args.check else date.today().isoformat()
        expected = render(creation_time, networks, review_date)
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        print(f"Unable to validate ChatGPT Voice source: {exc}", file=sys.stderr)
        return 2

    if args.check:
        if not TARGET.exists() or TARGET.read_text(encoding="utf-8") != expected:
            print("ChatGPTVoice.list is stale; run scripts/sync_chatgpt_voice.py", file=sys.stderr)
            return 1
        print(f"ChatGPT Voice snapshot is current ({len(networks)} prefixes)")
        return 0

    TARGET.write_text(expected, encoding="utf-8")
    print(f"Updated {TARGET.relative_to(ROOT)} with {len(networks)} prefixes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
